git clone git@github.com:Lisa-zxp/imagesbuild.git mkdir -vp imagesbuild/sig-storage/centos imagesbuild/sig-storage/centos/Dockerfile  <<'EOF'
FROM hub.docker.com/centos:centos7.9.2009
LABEL MAINTAINER=wangs BUILDTYPE=Aliyun
EOF git add . && git commit -m "centos" && git push
